#!/bin/bash
# Author(s) : Kenzo Hillion
# Contact : kenzo.hillion@curie.fr
# Comment(s) :
# 	cleaning_output.sh : Script to clean the files generated by ART


#### Parameters #### --------------------------------------------------------------------------------------------------------------

while [ $# -gt 0 ] 
do
    case "$1" in
    (-c) config=$2; shift;;
    (-h) usage;;
    (--) shift; break;;
    (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;; 
    (*)  break;;
    esac
    shift
done

if [[ -z $config ]]
then
    echo "ERROR : you need to specify a config file. Exit."
    exit
fi
source ${config}

#### Function #### ----------------------------------------------------------------------------------------------------------------

# Get args
function usage {
    echo -e "Usage : $0"
    echo -e "-c"" <Config file>"
    echo -e "-h"" <help>"
    exit
}

#### Main #### --------------------------------------------------------------------------------------------------------------------

# Merging SAM files and converting to BAM
echo -e "  |\t$(basename $0) : Rephasing SAM, merging files and converting to BAM ..."
for sam in `ls ${art_outdir}*.sam`
do
	if [[ ! -e ${art_outdir}HEADER.tmp ]]
	then
		head -2 ${sam} | awk -v chr=${chr} '{if ($1 ~ /^@SQ/) {$2="SN:chr"chr;print} else print}' OFS='\t' > ${art_outdir}HEADER.tmp
		grep '^@' ${sam} | tail -1 >> ${art_outdir}HEADER.tmp # Get the information of the program used to produced the data
	fi
	awk '{if ($1 !~ /^@/) {split($1,a,":"); split(a[2],b,"-"); $3=a[1]; $4=b[1]+$4; print}}' OFS='\t' ${sam} >> ${art_outdir}SAM.tmp
done

cat ${art_outdir}HEADER.tmp ${art_outdir}SAM.tmp | ${samtools} view -bS - > ${art_outdir}${id_geno1}_${id_geno2}.bam

# Merging .fq and compressing
echo -e "  |\t$(basename $0) : Merging .fq to ${art_outdir}${id_geno1}_${id_geno2}.fq.gz ..."
cat ${art_outdir}*.fq | gzip > ${art_outdir}${id_geno1}_${id_geno2}.fq.gz

# Removing temporary files and unused files
echo -e "  |\t$(basename $0) : Cleaning files ..."
rm ${art_outdir}*.tmp ${art_outdir}*.aln ${art_outdir}*.fq ${art_outdir}*.sam
